generals:
  clock_dt: 0.25
  end_time:
    val: 12.5
  debugger:
    use: true
    width: 720
    height: 720

  seed: 055c1509-cf2e-499a-9c79-e85ace6e654d

#map:
#  type: OsmGraph
#  latitude: 45.40008
#  longitude: -71.89908
#  zoom: 1200

map:
  type: PolarFileMap
  path: etc/sherbrooke_graph.json

systems:
  agents:
    - type: Accelerating

  clock:
    type: StandardClock

  controls: []

  logger:
    type: CsvLogger
    directory: "log_results" #This directory should be the same in the visualizer 
    files: []

  mobility:
    type: StandardMobility

  physic:
    type: Acceleration

  recorders: []

  spawner:
    type: Frequency
    min: 10
    max: 20
    start_locations:
      - 5872015933
      - 81474235
      - 4291399599
      - 4738061547
      - 110285445
      - 64010518
      - 3646823269
      - 110285457
      - 255785981
      - 2004727123
      - 3728506124
      - 110285459
      - 120943775
    end_locations:
      - 115710646
      - 4272197702
      - 2280297025
      - 4267279730
      - 4291399625
      - 1897554048

entities:
  - id: trafficlight01
    type: trafficlight
    light:
      initial_color: GREEN
      max_green_time: 5
      max_yellow_time: 1.5
      time: 3.5
    position: [[81474235, 81474556], 0.0]
    observable: trafficlight02
  - id: trafficlight02
    type: trafficlight
    light:
      initial_color: RED
      max_green_time: 3
      max_yellow_time: 1
      time: 0
    position: [[81474235, 81475573], 0.0]
    observable: trafficlight01
