generals:
  clock_dt: 0.10
  end_time:
    val: 1200
  debugger:
    use: true
    width: 360
    height: 360

  seed: 055c1509-cf2e-499a-9c79-e85ace6e654d

map:
  type: CartFileMap
  path: etc/square_graph.json

systems:
  agents:
    - type: Accelerating

  clock:
    type: StandardClock

  controls: []

  logger:
    type: CsvLogger
    directory: "log_results"
    files: []

  mobility:
    type: StandardMobility

  physic:
    type: Acceleration

  recorders: []

entities:
  - id: car01
    type: vehicle
    position: [[2, 3], 0.5]
    speed: 2
  - id: car02
    type: vehicle
    position: [[2, 3], 0.75]
    speed: 2
  - id: car03
    type: vehicle
    position: [[2, 3], 0.35]
    speed: 2
  - id: car04
    type: vehicle
    position: [[2, 3], 0.25]
    speed: 2
