generals:
  clock_dt: 0.25
  end_time:
    val: 12.5
  debugger:
    use: true
    width: 720
    height: 720
    
  seed: 055c1509-cf2e-499a-9c79-e85ace6e654d

# map:\
#   type: OsmGraph
#   latitude: -71.89908
#   longitude: 45.40008
#   zoom: 1200

map:
  type: FileMap
  path: etc/sherbrooke_graph.json

systems:
  agents:
    - type: Accelerating

  clock:
    type: StandardClock

  controls: []

  logger:
    type: CsvLogger
    directory: "log_results"
    files: []

  mobility:
    type: StandardMobility

  physic:
    type: Acceleration

  recorders:
    - capture_freq: 0
      type: CarPositionRecorder

  spawner:
    type: Frequency
    locations:
      - 1

entities:
  - id: vehicle01
    type: vehicle
    position:
      x: 0
      y: 0
    speed:
      val: 2
    spawner:
      type: Frequency
      period: 1
  - id: trafficlight01
    type: trafficlight
    light:
      initial_color: GREEN
      max_green_time: 5
      max_yellow_time: 1.5
      time: 3.5
    position:
      x: 150
      y: 100
    observable: trafficlight02
  - id: trafficlight02
    type: trafficlight
    light:
      initial_color: RED
      max_green_time: 3
      max_yellow_time: 1
      time: 0
    position:
      x: 400
      y: 100
    observable: trafficlight01
