generals:
  clock_dt: 0.25
  end_time:
    val: 12.5
  debugger:
    use: true
    width: 720
    height: 720

  seed: 055c1509-cf2e-499a-9c79-e85ace6e654d

map:
  type: OsmGraph
  latitude: 45.40008
  longitude: -71.89908
  zoom: 1200

#map:
#  type: FileMap
#  path: etc/sherbrooke_graph.json

systems:
  agents:
    - type: Accelerating

  clock:
    type: StandardClock

  controls: []

  logger:
    type: CsvLogger
    directory: "log_results"
    files: []

  mobility:
    type: StandardMobility

  physic:
    type: Acceleration

  recorders: []

  spawner:
    type: Frequency
    min: 10
    max: 20
    start_locations:
      - 5872015933
      - 81474235
      - 4291399599
      - 4738061547
      - 81591074
      - 64010518
      - 3646823269
      - 110285457
      - 255785981
      - 2004727123
      - 3728506124
      - 115677165
      - 120943775
    end_locations:
      - 1038872991
      - 4272197702

entities:
  - id: trafficlight01
    type: trafficlight
    light:
      initial_color: GREEN
      max_green_time: 5
      max_yellow_time: 1.5
      time: 3.5
    position: [-71.9103753, 45.4103252]
    observable: trafficlight02
  - id: trafficlight02
    type: trafficlight
    light:
      initial_color: RED
      max_green_time: 3
      max_yellow_time: 1
      time: 0
    position: [-71.9047379, 45.410244]
    observable: trafficlight01
